STATUSES = {
    0: "Opération effectuée avec succès",
    1: "Enseigne invalide",
    2: "Numéro d'enseigne vide ou inexistant",
    3: "Numéro de compte enseigne invalide",
    4: "",
    5: "Numéro de dossier enseigne invalide",
    6: "",
    7: "Numéro de client enseigne invalide (champ NCLIENT)",
    8: "Mot de passe ou hachage invalide",
    9: "Ville non reconnu ou non unique",
    10: "Type de collecte invalide",
    11: "Numéro de Relais de Collecte invalide",
    12: "Pays de Relais de collecte invalide",
    13: "Type de livraison invalide",
    14: "Numéro de Relais de livraison invalide",
    15: "Pays de Relais de livraison invalide",
    16: "",
    17: "",
    18: "",
    19: "",
    20: "Poids du colis invalide",
    21: "Taille (Longueur + Hauteur) du colis invalide",
    22: "Taille du Colis invalide",
    23: "",
    24: "Numéro d'expédition ou de suivi invalide",
    25: "",
    26: "Temps de montage invalide",
    27: "Mode de collecte ou de livraison invalide",
    28: "Mode de collecte invalide",
    29: "Mode de livraison invalide",
    30: "Adresse (L1) invalide",
    31: "Adresse (L2) invalide",
    32: "",
    33: "Adresse (L3) invalide",
    34: "Adresse (L4) invalide",
    35: "Ville invalide",
    36: "Code postal invalide",
    37: "Pays invalide",
    38: "Numéro de téléphone invalide",
    39: "Adresse e-mail invalide",
    40: "Paramètres manquants",
    41: "",
    42: "Montant CRT invalide",
    43: "Devise CRT invalide",
    44: "Valeur du colis invalide",
    45: "Devise de la valeur du colis invalide",
    46: "Plage de numéro d'expédition épuisée",
    47: "Nombre de colis invalide",
    48: "Multi-Colis Relais Interdit",
    49: "Action invalide",
    50: "",
    51: "",
    52: "",
    53: "",
    54: "",
    55: "",
    56: "",
    57: "",
    58: "",
    59: "",
    60: "Champ texte libre invalide (Ce code erreur n'est pas invalidant)",
    61: "Top avisage invalide",
    62: "Instruction de livraison invalide",
    63: "Assurance invalide",
    64: "Temps de montage invalide",
    65: "Top rendez-vous invalide",
    66: "Top reprise invalide",
    67: "Latitude invalide",
    68: "Longitude invalide",
    69: "Code Enseigne invalide",
    70: "Numéro de Point Relais invalide",
    71: "Nature de point de vente non valide",
    72: "",
    73: "",
    74: "Langue invalide",
    75: "",
    76: "",
    77: "",
    78: "Pays de Collecte invalide",
    79: "Pays de Livraison invalide",
    80: "Code tracing : Colis enregistré",
    81: "Code tracing : Colis en traitement chez Mondial Relay",
    82: "Code tracing : Colis livré",
    83: "Code tracing : Anomalie",
    84: "(Réservé Code Tracing)",
    85: "(Réservé Code Tracing)",
    86: "(Réservé Code Tracing)",
    87: "(Réservé Code Tracing)",
    88: "(Réservé Code Tracing)",
    89: "(Réservé Code Tracing)",
    90: "",
    91: "",
    92: "Le code pays du destinataire et le code pays du Point Relais doivent être identiques ou solde insuffisant (comptes prépayés).",
    93: "Aucun élément retourné par le plan de tri. Si vous effectuez une collecte ou une livraison en Point Relais, vérifiez que les Point Relais sont bien disponibles. Si vous effectuez une livraison à domicile, il est probable que le code postal que vous avez indiqué n'existe pas.",
    94: "Colis Inexistant",
    95: "Compte Enseigne non activé",
    96: "Type d'enseigne incorrect en Base",
    97: "Clé de sécurité invalide",
    98: "Erreur générique (Paramètres invalides)",
    99: "Erreur générique du service",
}
